# Generated by Django 4.2.1 on 2023-06-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecMgt_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="is_dept", field=models.BooleanField(default=False),
        ),
    ]
