# Generated by Django 4.2.1 on 2023-06-04 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lecMgt_auth", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Leave",),
    ]
