# Generated by Django 4.2.1 on 2023-06-03 01:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("lecMgt_auth", "0002_user_is_dept"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dept_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("dept_title", models.CharField(max_length=30, unique=True)),
            ],
            options={"verbose_name_plural": "Departments", "db_table": "Department",},
        ),
    ]
