# Generated by Django 4.2.1 on 2023-06-20 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("lecMgt_auth", "0004_notice"),
    ]

    operations = [
        migrations.CreateModel(
            name="LecturerProfile",
            fields=[
                (
                    "profile_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("grade_point", models.IntegerField(default=8)),
            ],
            options={
                "verbose_name_plural": "Lecturer Profile",
                "db_table": "Lecturer Profile",
            },
        ),
        migrations.CreateModel(
            name="Positions",
            fields=[
                (
                    "pos_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("position_title", models.CharField(max_length=50, unique=True)),
            ],
            options={"verbose_name_plural": "Positions", "db_table": "Positions",},
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "qua_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("qua_title", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name_plural": "Qualification",
                "db_table": "Qualification",
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "pro_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("dept_approval", models.BooleanField(default=False)),
                ("central_approval", models.BooleanField(default=False)),
                ("dean_approval", models.BooleanField(default=False)),
                ("hod_approval", models.BooleanField(default=False)),
                (
                    "lecturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lecMgt_auth.lecturerprofile",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lecMgt_auth.positions",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Promotion", "db_table": "Promotion",},
        ),
        migrations.AddField(
            model_name="lecturerprofile",
            name="lec_qua",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lecMgt_auth.qualification",
            ),
        ),
        migrations.AddField(
            model_name="lecturerprofile",
            name="position",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lecMgt_auth.positions",
            ),
        ),
        migrations.AddField(
            model_name="lecturerprofile",
            name="user_id",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
