# Generated by Django 4.2.1 on 2023-06-04 00:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("lecMgt_auth", "0005_alter_department_dept_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTypes",
            fields=[
                (
                    "type_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("user_Type", models.CharField(max_length=50, unique=True)),
            ],
            options={"verbose_name_plural": "User Types", "db_table": "User Type",},
        ),
    ]
