# Generated by Django 4.2.1 on 2023-06-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lecMgt_auth",
            "0005_lecturerprofile_positions_qualification_promotion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="qua_abbr",
            field=models.CharField(default="", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
