# Generated by Django 4.2.1 on 2023-06-20 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecMgt_auth", "0006_qualification_qua_abbr"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturerprofile",
            name="employment_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 20, 19, 42, 36, 845447, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="positions",
            name="position_grade",
            field=models.IntegerField(default=8),
        ),
    ]
