# Generated by Django 4.2.1 on 2023-06-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lecMgt_auth", "0007_lecturerprofile_employment_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="lecturerprofile", name="position",),
    ]
