# Generated by Django 4.2.1 on 2023-06-21 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lecMgt_auth", "0008_remove_lecturerprofile_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturerprofile",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lecMgt_auth.positions",
            ),
        ),
    ]
