# Generated by Django 4.2.1 on 2023-06-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecMgt_auth", "0009_lecturerprofile_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="date_applied",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
