# Generated by Django 4.2.1 on 2023-06-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecMgt_auth", "0010_promotion_date_applied"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="is_pending",
            field=models.BooleanField(default=True),
        ),
    ]
