# Generated by Django 4.2.1 on 2023-06-21 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lecMgt_auth", "0011_promotion_is_pending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturerprofile",
            name="employment_date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
