# Generated by Django 4.2.1 on 2023-07-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecMgt_auth", "0013_notice_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="notice_title",
            field=models.CharField(max_length=50),
        ),
    ]
