# Generated by Django 4.2.1 on 2023-07-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecMgt_auth", "0014_alter_notice_notice_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="central_disapproval_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotion",
            name="dean_disapproval_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotion",
            name="dept_disapproval_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotion",
            name="hod_disapproval_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
